### ISSUE TITLE
Manhattan prompt to save even without changes

### ISSUE THREAD

**Issue by nashnet** [nashnet/manhattan-issues#10]
- If you have just saved a song, and want to load another one, it would be neat to detect that there are no unsaved changes, and the next song is just loaded without needlessly warning the user.

**Comment by nashnet** [comment]
This should be what happens already. Maybe that a recent code update is spuriously registering as a change.

**Comment by esaruoho** [comment]
I'll post a .gif to demonstrate.
![save gif save gif](https://github.com/nashnet/manhattan-issues/assets/4966687/6713ccbe-3e3f-45e7-b689-f13296f48125)
here's two different methods - one where i save and then load something else, and it tells me stuff. then another where i save and then quit - and it tells me stuff.

**Comment by nashnet** [comment]
Fixed - new or freshly loaded and saved songs should no longer prompt.
